# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chrome_runner_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChromeRunnerDialog(object):
    def setupUi(self, ChromeRunnerDialog):
        ChromeRunnerDialog.setObjectName("ChromeRunnerDialog")
        ChromeRunnerDialog.resize(822, 788)
        self.gridLayout = QtWidgets.QGridLayout(ChromeRunnerDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ChromeRunnerDialog)
        self.label.setMinimumSize(QtCore.QSize(0, 29))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.chrome_list_widget = QtWidgets.QListWidget(ChromeRunnerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chrome_list_widget.sizePolicy().hasHeightForWidth())
        self.chrome_list_widget.setSizePolicy(sizePolicy)
        self.chrome_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.chrome_list_widget.setObjectName("chrome_list_widget")
        self.verticalLayout.addWidget(self.chrome_list_widget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(ChromeRunnerDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.add_web_btn = QtWidgets.QPushButton(ChromeRunnerDialog)
        self.add_web_btn.setObjectName("add_web_btn")
        self.horizontalLayout_2.addWidget(self.add_web_btn)
        self.edit_web_btn = QtWidgets.QPushButton(ChromeRunnerDialog)
        self.edit_web_btn.setObjectName("edit_web_btn")
        self.horizontalLayout_2.addWidget(self.edit_web_btn)
        self.delete_web_btn = QtWidgets.QPushButton(ChromeRunnerDialog)
        self.delete_web_btn.setObjectName("delete_web_btn")
        self.horizontalLayout_2.addWidget(self.delete_web_btn)
        self.refresh_btn = QtWidgets.QPushButton(ChromeRunnerDialog)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_2.addWidget(self.refresh_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.web_list_widget = QtWidgets.QListWidget(ChromeRunnerDialog)
        self.web_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.web_list_widget.setObjectName("web_list_widget")
        self.verticalLayout_2.addWidget(self.web_list_widget)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.status_label = QtWidgets.QLabel(ChromeRunnerDialog)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.reset_iterator_btn = QtWidgets.QPushButton(ChromeRunnerDialog)
        self.reset_iterator_btn.setObjectName("reset_iterator_btn")
        self.horizontalLayout.addWidget(self.reset_iterator_btn)
        self.run_next_btn = QtWidgets.QPushButton(ChromeRunnerDialog)
        self.run_next_btn.setObjectName("run_next_btn")
        self.horizontalLayout.addWidget(self.run_next_btn)
        self.run_btn = QtWidgets.QPushButton(ChromeRunnerDialog)
        self.run_btn.setObjectName("run_btn")
        self.horizontalLayout.addWidget(self.run_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)

        self.retranslateUi(ChromeRunnerDialog)
        QtCore.QMetaObject.connectSlotsByName(ChromeRunnerDialog)

    def retranslateUi(self, ChromeRunnerDialog):
        _translate = QtCore.QCoreApplication.translate
        ChromeRunnerDialog.setWindowTitle(_translate("ChromeRunnerDialog", "Chrome 启动器"))
        self.label.setText(_translate("ChromeRunnerDialog", "Chrome列表："))
        self.label_2.setText(_translate("ChromeRunnerDialog", "启动网站："))
        self.add_web_btn.setText(_translate("ChromeRunnerDialog", "添加"))
        self.edit_web_btn.setText(_translate("ChromeRunnerDialog", "修改"))
        self.delete_web_btn.setText(_translate("ChromeRunnerDialog", "删除"))
        self.refresh_btn.setText(_translate("ChromeRunnerDialog", "刷新列表"))
        self.status_label.setText(_translate("ChromeRunnerDialog", "TextLabel"))
        self.reset_iterator_btn.setText(_translate("ChromeRunnerDialog", "从头开始"))
        self.run_next_btn.setText(_translate("ChromeRunnerDialog", "按选中项迭代启动"))
        self.run_btn.setText(_translate("ChromeRunnerDialog", "启动选中（批量）"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChromeRunnerDialog = QtWidgets.QDialog()
    ui = Ui_ChromeRunnerDialog()
    ui.setupUi(ChromeRunnerDialog)
    ChromeRunnerDialog.show()
    sys.exit(app.exec_())
